//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfCVProjeDemo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBCVEFrameworkEntities : DbContext
    {
        public DBCVEFrameworkEntities()
            : base("name=DBCVEFrameworkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Adres> Adres { get; set; }
        public virtual DbSet<Calismalarim> Calismalarim { get; set; }
        public virtual DbSet<Hakkımda> Hakkımda { get; set; }
        public virtual DbSet<İletisim> İletisim { get; set; }
        public virtual DbSet<Yetenekler> Yetenekler { get; set; }
    }
}
